//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Manager
    {
        public string Job { get; set; }
        public int ManagerId { get; set; }
        public System.DateTime HireDate { get; set; }
        public int Salary { get; set; }
        public int AddressId { get; set; }
        public int ProjectId { get; set; }
    }
}
